EXT_CFLAGS+="-DPOLYBENCH_TIME"
EXT_CFLAGS+="-DEXTRALARGE_DATASET"
EXT_CFLAGS+="-DPARALLEL_OPT"
EXT_CFLAGS+="-DINNERMOST_LOOP_PROFILING_TOGGLE=INNERMOST_LOOP_PROFILING_ENABLE"
#EXT_CFLAGS+="-DDATA_TYPE=double"

